### ISSUE TITLE
elm-test init creates broken. project-json on 0.18.0

### ISSUE THREAD

**Issue by zkessin** [rtfeldman/node-test-runner#94]
I . got this json but 4 of the modules are on the wrong versions
```
{
    "version": "1.0.0",
    "summary": "Sample Elm Test",
    "repository": "https://github.com/user/project.git",
    "license": "BSD-3-Clause",
    "source-directories": [
        ".",
        "../src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-community/json-extra": "1.0.0 <= v < 2.0.0",
        "elm-lang/html": "1.0.0 <= v < 2.0.0",
        "mgold/elm-random-pcg": "3.0.0 <= v < 4.0.0",
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-community/elm-test": "3.0.0 <= v < 4.0.0",
        "rtfeldman/node-test-runner": "3.0.0 <= v < 4.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

```

--> Your elm-package.json has the following dependency:
    
        "elm-community/json-extra": "1.0.0 <= v < 2.0.0"
    
    But none of the versions in that range work with Elm 0.18.0. I recommend
    removing that dependency by hand and adding it back with:
    
        elm-package install elm-community/json-extra 2.0.0

--> Your elm-package.json has the following dependency:
    
        "mgold/elm-random-pcg": "3.0.0 <= v < 4.0.0"
    
    But none of the versions in that range work with Elm 0.18.0. I recommend
    removing that dependency by hand and adding it back with:
    
        elm-package install mgold/elm-random-pcg 4.0.2

--> Your elm-package.json has the following dependency:
    
        "elm-lang/html": "1.0.0 <= v < 2.0.0"
    
    But none of the versions in that range work with Elm 0.18.0. I recommend
    removing that dependency by hand and adding it back with:
    
        elm-package install elm-lang/html 2.0.0


Compilation failed for Main.elm
```

**Comment by rtfeldman** [comment]
Fixed in https://github.com/rtfeldman/node-test-runner/pull/93
